# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GaussianKernel <- function(x1, x2, kernelPar) {
    .Call('TempShift_GaussianKernel', PACKAGE = 'TempShift', x1, x2, kernelPar)
}

